#!/bin/sh
. "$HOME/.cache/wal/colors.sh"

WARNING_LEVEL=80

CPU_TEMP="$(sensors 2>/dev/null | awk '/Core 0/ {gsub(/[^0-9.]/, "", $3); printf "%d", $3}')"

if [ "$CPU_TEMP" -ge "$WARNING_LEVEL" ]; then
    printf "^c${color9}^🌡 %s°C^d^" "$CPU_TEMP"
else
    printf "^c${color5}^🌡 %s°C^d^" "$CPU_TEMP"
fi
